const API_BASE="https://netflix-api-g992.onrender.com";
let currentUser=null,currentMedia=null,allMedia=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function api(path,options={}){const res=await fetch(API_BASE+path,{...options,credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})}});let data=null;try{data=await res.json()}catch{}if(!res.ok)throw new Error(typeof data==="string"?data:data?.message||"Request failed");return data}
function setStatus(msg){$("status").textContent=msg||""}
function mediaImage(x){return x?.image||""}
function render(id,items){const el=$(id);if(!el)return;if(!items?.length){el.innerHTML='<div class="empty">Nothing here yet.</div>';return}el.innerHTML=items.map((x,i)=>'<article class="card" data-index="'+i+'"><img class="poster" src="'+esc(mediaImage(x))+'" alt="'+esc(x.title)+'" loading="lazy" onerror="this.style.display=\'none\'"><div class="card-title">'+esc(x.title)+'</div></article>').join("");el.querySelectorAll(".card").forEach(c=>c.onclick=()=>openModal(items[+c.dataset.index]))}
function openModal(item){currentMedia=item;$("modalTitle").textContent=item.title||"Untitled";$("modalDescription").textContent=item.description||"No description available.";const genres=item.genre||[];$("modalGenres").innerHTML=genres.map(g=>"<span>"+esc(g)+"</span>").join("");$("modalMeta").textContent=[item.type,item.rating?"★ "+item.rating:"",item.release_date?new Date(item.release_date).getFullYear():""].filter(Boolean).join(" • ");$("modalPoster").style.backgroundImage=item.image?'url("'+item.image+'")':"none";$("modal").classList.add("open");document.body.classList.add("lock")}
function closeModal(){$("modal").classList.remove("open");document.body.classList.remove("lock")}
function openAuth(mode="login"){$("auth").dataset.mode=mode;$("authTitle").textContent=mode==="login"?"Sign in":"Create account";$("authSubmit").textContent=mode==="login"?"Sign in":"Create account";$("username").style.display=mode==="login"?"none":"block";$("switchAuth").textContent=mode==="login"?"Create a new account":"Already have an account? Sign in";$("authMessage").textContent="";$("auth").classList.add("open");document.body.classList.add("lock")}
function closeAuth(){$("auth").classList.remove("open");document.body.classList.remove("lock")}
async function loadHome(){setStatus("Loading your library…");try{allMedia=await api("/data/media");render("trending",allMedia);render("moviesRow",allMedia.filter(x=>String(x.type).toLowerCase()==="movie"));render("seriesRow",allMedia.filter(x=>["tvshow","series"].includes(String(x.type).toLowerCase())));if(currentUser){try{render("watchlistRow",await api("/data/media/watchlist/"+currentUser._id))}catch{render("watchlistRow",[]) }try{const rec=await api("/data/media/recommend/"+currentUser._id);render("recommendedRow",Array.isArray(rec)?rec.flatMap(x=>x.movie?[x.movie].flat():[]):[])}catch{render("recommendedRow",[])}}else{render("watchlistRow",[]);render("recommendedRow",[])}setStatus(allMedia.length+" titles available")}catch(e){setStatus("Please sign in to load the catalog.")}}
async function loadProfile(){try{currentUser=await api("/user/profile");$("accountBtn").textContent=currentUser.username||"Account";await loadHome()}catch{currentUser=null;$("accountBtn").textContent="Sign in";render("watchlistRow",[]);render("recommendedRow",[]);setStatus("Sign in to access Net Mirror.")}}
$("authForm").onsubmit=async e=>{e.preventDefault();const mode=$("auth").dataset.mode;const msg=$("authMessage");msg.textContent="Please wait…";try{if(mode==="login"){await api("/user/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});await loadProfile();closeAuth()}else{await api("/user/register",{method:"POST",body:JSON.stringify({username:$("username").value,email:$("email").value,password:$("password").value})});msg.textContent="Account created. Sign in now.";openAuth("login")}}catch(err){msg.textContent=err.message}}
$("switchAuth").onclick=()=>openAuth($("auth").dataset.mode==="login"?"register":"login");$("accountBtn").onclick=()=>currentUser?logout():openAuth("login");
async function logout(){try{await api("/user/logout");currentUser=null;$("accountBtn").textContent="Sign in";render("watchlistRow",[]);render("recommendedRow",[]);setStatus("Signed out.")}catch(e){setStatus(e.message)}}
$("refreshBtn").onclick=loadHome;$("closeAuth").onclick=closeAuth;$("closeModal").onclick=closeModal;
$("moreFeatured").onclick=()=>allMedia[0]&&openModal(allMedia[0]);$("playFeatured").onclick=()=>allMedia[0]&&openModal(allMedia[0]);
$("modalWatchlist").onclick=async()=>{if(!currentUser)return openAuth("login");if(!currentMedia)return;try{await api("/data/media/watchlist/"+currentMedia._id+"/"+currentUser._id,{method:"POST"});setStatus("Added to watchlist.");await loadHome()}catch(e){setStatus(e.message)}};
$("modalPlay").onclick=async()=>{if(!currentUser)return openAuth("login");if(!currentMedia)return;try{await api("/data/media/stream/"+currentMedia._id+"/"+currentUser._id,{method:"POST"});const stream=currentMedia.movie_stream;if(stream&&/^https?:\/\//i.test(stream)){$("video").src=stream;$("playerMessage").textContent="";$("player").classList.add("open");document.body.classList.add("lock");$("video").play().catch(()=>{})}else{$("playerMessage").textContent="This API currently records the watch in history, but its movie_stream field is not a playable video URL.";$("player").classList.add("open");document.body.classList.add("lock")}}catch(e){setStatus(e.message)}};
$("closePlayer").onclick=()=>{$("player").classList.remove("open");$("video").pause();$("video").removeAttribute("src");document.body.classList.remove("lock")};
$("searchBtn").onclick=()=>{$("searchOverlay").classList.add("open");$("searchInput").focus()};$("closeSearch").onclick=()=>$("searchOverlay").classList.remove("open");
$("searchInput").oninput=async e=>{const q=e.target.value.trim();if(!q){$("searchResults").innerHTML="";return}try{const results=await api("/data/media/search/"+encodeURIComponent(q));render("searchResults",results)}catch(err){$("searchResults").innerHTML='<div class="empty">'+esc(err.message)+"</div>"}};
window.addEventListener("scroll",()=>document.querySelector(".nav").style.background=scrollY>30?"#050505ee":"linear-gradient(#050505,transparent)");
loadProfile();